@Makeos_HostAddress = http://localhost:5225

POST {{Makeos_HostAddress}}/PDFExtractor/GetTextFromPdf
Content-Type: multipart/form-data; boundary=----Boundary

------Boundary
Content-Disposition: form-data; name="file"; filename="ejemplo.pdf"
Content-Type: application/pdf

< ./ejemplo.pdf
------Boundary--

###
